name: Build Release Artifacts

on:
push:
     branches: [release-artifacts]
  workflow_dispatch:

jobs:

  release-artifacts:
    runs-on: ubuntu-latest
      steps:

    - uses: actions/checkout@v2

    - name: Set up environment
      uses: ./.github/actions/setup-rel-env
      
    - name: Build vdb-gen
        run: make vdb-gen

    - name: Build CRD yaml
        run: make generate manifests create-helm-charts

    - name: Build RBAC yaml
        run: make create-default-rbac

    - name: Build helm charts
      run: | 
        make generate manifests create-helm-charts
        cd helm-charts && helm package verticadb-operator
       

    - uses: actions/upload-artifact@v2
      if: always()
      continue-on-error: false
      with:
        name: release-artifacts
          path: /home/runner/work/vertica-kubernetes/vertica-kubernetes/helm-charts/verticadb-operator/crds/verticadbs.vertica.com-crd.yaml 

    - uses: actions/upload-artifact@v2
      if: always()
      continue-on-error: false
      with:
        name: release-artifacts
          path: /home/runner/work/vertica-kubernetes/vertica-kubernetes/config/samples/custom-scc.yaml
    
    - uses: actions/upload-artifact@v2
      if: always()
      continue-on-error: false
      with:
        name: release-artifacts
          path: /home/runner/work/vertica-kubernetes/config/samples/rbac/default-rbac.yaml

    - uses: actions/upload-artifact@v2
      if: always()
      continue-on-error: false
      with:
        name: release-artifacts
          path: /home/runner/work/vertica-kubernetes/helm-charts

    - uses: actions/upload-artifact@v2
      if: always()
      continue-on-error: false
      with:
        name: release-artifacts
          path: /home/runner/work/vertica-kubernetes/bin/vdb-gen

    - uses: actions/upload-artifact@v2
      if: always()
      continue-on-error: false
      with:
        name: release-artifacts
          path: /home/runner/work/vertica-kubernetes/bundle
    

    



        
