name: Build Release Artifacts

on: 
  push:
    branches: [release-artifacts]
  workflow_dispatch:

jobs:
  release-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up environment
      uses: ./.github/actions/setup-rel-env
    
    - name: Install krew
      run: | 
        make krew
        export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

    - name: Build CRD yaml
      run: make generate manifests
    
    - name: Lint the charts
      run: make lint

    - name: Build vdb-gen
      run: | 
        mkdir bin
        make vdb-gen

    - name: Build RBAC yaml
      run: |
        mkdir config/samples/rbac
        make create-default-rbac

    - name: Build helm charts
      run: | 
        make create-helm-charts
        cd helm-charts
        helm package verticadb-operator
       
    - name: Upload CRD
    - uses: actions/upload-artifact@v2
      if: always()
      continue-on-error: false
      with:
        name: release-artifacts
        path: /home/runner/work/vertica-kubernetes/vertica-kubernetes/helm-charts/verticadb-operator/crds/verticadbs.vertica.com-crd.yaml 

    - name: Upload Custom SCC
    - uses: actions/upload-artifact@v2
      if: always()
      continue-on-error: false
      with:
        name: release-artifacts
        path: /home/runner/work/vertica-kubernetes/vertica-kubernetes/config/samples/custom-scc.yaml
    
    - name: Upload Default RBAC
    - uses: actions/upload-artifact@v2
      if: always()
      continue-on-error: false
      with:
        name: release-artifacts
        path: /home/runner/work/vertica-kubernetes/config/samples/rbac/default-rbac.yaml

    - name: Upload Helm Charts
    - uses: actions/upload-artifact@v2
      if: always()
      continue-on-error: false
      with:
        name: release-artifacts
        path: /home/runner/work/vertica-kubernetes/helm-charts/*.tgz

    - name: Upload vdb-gen
    - uses: actions/upload-artifact@v2
      if: always()
      continue-on-error: false
      with:
        name: release-artifacts
        path: /home/runner/work/vertica-kubernetes/bin/vdb-gen

    - name: Upload bundle
    - uses: actions/upload-artifact@v2
      if: always()
      continue-on-error: false
      with:
        name: release-artifacts
        path: /home/runner/work/vertica-kubernetes/bundle
    

    



        
